-- TABELA DE PRODUTOS VENDIDOS
CREATE TABLE vendas_cestas (
    id SERIAL PRIMARY KEY,
    cesta_id INT NOT NULL,
    preco_pago DECIMAL(10, 2) NOT NULL,
    pago BOOLEAN NOT NULL DEFAULT FALSE,
    data_venda TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);